### ISSUE TITLE
Workflow checklist

### ISSUE THREAD

**Issue by GuiyuanLei** [githubteacher/welwyn-dec-2016#12]
## Class Checklist
- [x] Create an Issue
- [ ] Create a Branch
- [ ] Make commits
- [ ] Open a pull request
- [ ] Collaborate!
- [ ] Merge pull request
- [ ] Have a great time! :sparkler:
